title: Blog's Nam
name: Hoang Nam
email: nhatnam10a3@gmail.com
description: When life changes to be harder, change yourself to be stronger.

baseurl: "/blog"
url: Ti

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "Chat Project"
project_one_description: Chat Zone  By Me In HasBrain!
project_one_url: http://testhasbrain.herokuapp.com/
project_one_icon: location_on

project_two: Best Price
project_two_description: Compare Price By Me In HasBrain!
project_two_url: http://bestcomparison.herokuapp.com/
project_two_icon: photo_camera

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: android
  - name: c
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: git
  - name: html5
  - name: java
  - name: javascript
  - name: mysql
  - name: nodejs
  - name: oracle
  - name: photoshop
  - name: php
  - name: python
  - name: visualstudio

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Visit

#facebook: https://www.facebook.com/hcnnam.bku
#medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
